
# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH
export PATH=$PATH":$HOME/bin"
export PATH=$PATH":/usr/local/bin/gdb"
export PATH=$PATH":/usr/local/mysql/bin"
export PATH=$PATH":/opt/apache-maven-3.3.9/bin"
export PATH=$PATH":/opt/mongodb-osx-x86_64-3.2.3/bin"
export CLASSPATH=$CLASSPATH:/Users/zhongzhu/Downloads/prism-4.3-osx64/lib
export CLICOLOR=1
export LSCOLORS=exFxCxDxbxegedabagaced
export STANFORDTOOLSDIR=$HOME/Downloads
export CLASSPATH=$STANFORDTOOLSDIR/stanford-postagger-full-2015-04-20/stanford-postagger.jar:$STANFORDTOOLSDIR/stanford-ner-2015-04-20/stanford-ner.jar:$STANFORDTOOLSDIR/stanford-parser-full-2015-04-20/stanford-parser.jar:$STANFORDTOOLSDIR/stanford-parser-full-2015-04-20/stanford-parser-3.5.2-models.jar
export STANFORD_MODELS=$STANFORDTOOLSDIR/stanford-postagger-full-2015-04-20/models:$STANFORDTOOLSDIR/stanford-ner-2015-04-20/classifiers

alias gdb="/usr/local/bin/gdb/gdb"
alias cdcmu="cd ~/Dropbox/CMU/"
alias cdws="cd ~/Documents/workspace/"
alias cdruby="cd ~/Documents/Code/ruby/ruby\ koans/"
alias cdnode="cd ~/Documents/code/node"
alias shark="~/Private/shark.sh"
alias afs="~/Private/afs.sh"
#alias cdics="cd ~/Dropbox/CMU/15513\ Introduction\ to\ Computer\ Systems/"
alias ll="ls -l"
alias l="ls -l"
alias c="clear"





#1. directory 
#2. symbolic link 
#3. socket 
#4. pipe 
#5. executable 
#6. block special 
#7. character special 
#8. executable with setuid bit set 
#9. executable with setgid bit set 
#10. directory writable to others, with sticky bit 
#11. directory writable to others, without sticky 

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=/Applications/Cocos/frameworks/cocos2d-x-3.6/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH

# Add environment variable COCOS_FRAMEWORKS for cocos2d-x
export COCOS_FRAMEWORKS=/Applications/Cocos/frameworks
export PATH=$COCOS_FRAMEWORKS:$PATH

# Add environment variable ANT_ROOT for cocos2d-x
export ANT_ROOT=/Applications/Cocos/tools/ant/bin
export PATH=$ANT_ROOT:$PATH
